id: I0C141CE2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:56:25+00:00'
last_modified: '2022-06-07T12:01:50.937779+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN471
  title: པཎ་ཆེན་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་མཛད་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AD26:
      image_group_id: I3CN7136
      title: Volume 1 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 338
      order: 1
      base_file: AD26.txt
    2C63:
      image_group_id: I3CN7137
      title: Volume 2 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 412
      order: 2
      base_file: 2C63.txt
    4F96:
      image_group_id: I3CN7138
      title: Volume 3 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 580
      order: 3
      base_file: 4F96.txt
    D321:
      image_group_id: I3CN7139
      title: Volume 4 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 444
      order: 4
      base_file: D321.txt
    D5BD:
      image_group_id: I3CN7140
      title: Volume 5 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 432
      order: 5
      base_file: D5BD.txt
    444F:
      image_group_id: I3CN7141
      title: Volume 6 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 438
      order: 6
      base_file: 444F.txt
    '1884':
      image_group_id: I3CN7142
      title: Volume 7 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 479
      order: 7
      base_file: 1884.txt
    1D2D:
      image_group_id: I3CN7143
      title: Volume 8 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 356
      order: 8
      base_file: 1D2D.txt
    '3262':
      image_group_id: I3CN7144
      title: Volume 9 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 370
      order: 9
      base_file: 3262.txt
    C984:
      image_group_id: I3CN7145
      title: Volume 10 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 536
      order: 10
      base_file: C984.txt
    1CFC:
      image_group_id: I3CN7146
      title: Volume 11 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 508
      order: 11
      base_file: 1CFC.txt
    BB87:
      image_group_id: I3CN7147
      title: Volume 12 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 566
      order: 12
      base_file: BB87.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
